rollbackableTasks:
    - name: "stage1"
      cluster: "test"
      applyTime: "time"
      maxRollingUpdateParallelNum: 3
      maxParallelNum: 5
      needApproveToStart: true
      tasks:
        - taskName: "tsk1"
          taskType: "no_rolling_update"
          needApproveToStart: false
